# Generated by Django 4.1.7 on 2023-03-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_pup_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pup_date",
            field=models.DateField(),
        ),
    ]
