# Generated by Django 4.1.7 on 2023-03-18 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_book_pup_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": (
                    (
                        "can_create_more_than_one_book",
                        "can create more than than one book",
                    ),
                )
            },
        ),
    ]
