# Generated by Django 4.1.7 on 2023-03-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0010_sale_category_book_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="categories",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
